pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
		stage('Manual Approval') {
	        input {
	            message 'Please select environment'
	            id 'envId'
	            ok 'Submit'
	            submitterParameter 'approverId'
	            parameters {
					choice choices: ['Prod', 'Pre-Prod'], name: 'envType'
	            }
	        }

	        steps {
	            echo "Deployment approved to ${envType} by ${approverId}."
	        }
	    }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the website? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
